name: gestu_menu
description: >
  A customizable and animated menu package for Flutter that provides primary
  and secondary menu items.
version: 0.0.2
homepage: https://gestu.dev
repository: https://github.com/GestuDev/gestu_menu.git

environment:
  sdk: ">=3.4.1 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
